#!/usr/bin/env python3
"""Build cumulative human-readable markdown counterparts for data/.

Reads every JSON snapshot under data/{daily,weekly,monthly}/ and writes
three aggregated markdown files at the dataset root, refreshed each
scrape:

    data/daily.md    - one section per daily snapshot, newest first
    data/weekly.md   - one section per weekly snapshot, newest first
    data/monthly.md  - one section per monthly snapshot, newest first

Pure stdlib; intentionally writeable from any Python 3.12 environment
without installing the trending package.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
DATA_DIR = REPO_ROOT / "data"


def escape_pipe(text: str | None) -> str:
    """Escape `|` so it doesn't break a markdown pipe-table cell.

    Idempotent: an already-escaped string is returned unchanged.
    """
    if text is None:
        return ""
    out: list[str] = []
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "\\" and i + 1 < len(text) and text[i + 1] == "|":
            out.append("\\|")
            i += 2
            continue
        if ch == "|":
            out.append("\\|")
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def format_int(n: int) -> str:
    """Render integers with comma thousands separators."""
    return f"{n:,}"


def build_section(
    *,
    json_path: Path,
    snapshot: dict,
    emoji: str,
    title: str,
) -> str:
    """Render a single snapshot as a markdown section.

    `json_path` is expressed relative to the markdown file's directory
    (i.e. `daily/2026-05-14.json`, NOT an absolute path) so the link
    works on GitHub.
    """
    period = snapshot["period"]
    items = snapshot["items"]

    lines: list[str] = []
    lines.append(
        f"## {period['start']} — {emoji} {title} "
        f"(window `{period['label_compact']}`)"
    )
    lines.append("")
    lines.append(
        f"Captured at `{snapshot['run_date_utc']}` · "
        f"{snapshot['count']} repos · "
        f"[raw JSON]({json_path.as_posix()})"
    )
    lines.append("")
    lines.append(
        "| # | Repo | Lang | ⭐ total | Forks | Period ⭐ | Description |"
    )
    lines.append(
        "|--:|------|------|-------:|------:|---------:|-------------|"
    )
    for item in items:
        repo_link = (
            f"[{escape_pipe(item['full_name'])}]"
            f"({item['url']})"
        )
        lang = escape_pipe(item.get("language") or "—")
        desc = escape_pipe(item.get("description") or "")
        lines.append(
            f"| {item['rank']} | {repo_link} | {lang} | "
            f"{format_int(item['stars_total'])} | "
            f"{format_int(item['forks_total'])} | "
            f"**{format_int(item['period_stars'])}** | {desc} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def build_file(
    *,
    granularity: str,
    title: str,
    emoji: str,
    pairs: list[tuple[Path, dict]],
) -> str:
    """Assemble the full cumulative markdown body for one granularity.

    `pairs` come in chronological order (oldest first) from
    `read_snapshots`. The output renders them newest-first.
    """
    parts: list[str] = []
    parts.append(f"# {title} — accumulated snapshots")
    parts.append("")
    if pairs:
        oldest = pairs[0][1]["period"]["start"]
        newest = pairs[-1][1]["period"]["start"]
        parts.append(
            f"Auto-generated by `build_markdown.py` from "
            f"`data/{granularity}/*.json` on every scrape. "
            f"**{len(pairs)} snapshots** spanning "
            f"`{oldest}` → `{newest}`. "
            f"Raw JSON: [`data/{granularity}/`]({granularity}/)."
        )
    else:
        parts.append(
            f"Auto-generated by `build_markdown.py` from "
            f"`data/{granularity}/*.json` on every scrape. "
            f"**0 snapshots** so far."
        )
    parts.append("")
    parts.append("---")
    parts.append("")
    for json_path, snapshot in reversed(pairs):
        parts.append(
            build_section(
                json_path=json_path,
                snapshot=snapshot,
                emoji=emoji,
                title=title,
            )
        )
    return "\n".join(parts).rstrip() + "\n"


def read_snapshots(data_dir: Path, granularity: str) -> list[tuple[Path, dict]]:
    """Load all `<data_dir>/<granularity>/*.json` files in chronological order.

    A file that fails to parse is logged to stderr and skipped — one
    corrupt JSON should not block rebuilding the markdown for the
    remaining snapshots.
    """
    folder = data_dir / granularity
    if not folder.exists():
        return []
    pairs: list[tuple[Path, dict]] = []
    for path in sorted(folder.glob("*.json")):
        try:
            pairs.append((path, json.loads(path.read_text(encoding="utf-8"))))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"warn: skipping unreadable {path}: {exc}", file=sys.stderr)
    return pairs


_GRANULARITIES = (
    ("daily", "Daily Trending", "🔥"),
    ("weekly", "Weekly Trending", "📅"),
    ("monthly", "Monthly Trending", "🗓️"),
)


def write_file(target: Path, body: str) -> None:
    """Atomic write: tempfile + os.replace (same pattern as snapshot.py)."""
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp_fd, tmp_path = tempfile.mkstemp(
        prefix=".build-markdown-",
        suffix=".md.tmp",
        dir=str(target.parent),
    )
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            f.write(body)
        os.replace(tmp_path, target)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            # Best-effort cleanup; never suppress the original exception.
            pass
        raise


def main() -> int:
    for granularity, title, emoji in _GRANULARITIES:
        pairs = read_snapshots(DATA_DIR, granularity)
        # Convert absolute snapshot paths to ones relative to DATA_DIR so the
        # `[raw JSON](...)` links inside the markdown work on GitHub.
        pairs = [(p.relative_to(DATA_DIR), s) for p, s in pairs]
        body = build_file(
            granularity=granularity,
            title=title,
            emoji=emoji,
            pairs=pairs,
        )
        target = DATA_DIR / f"{granularity}.md"
        write_file(target, body)
        print(f"wrote {target} ({len(pairs)} snapshots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
